---
- name: helm add repo
  command: "helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/"

- name: helm install prometheus operator
  command: "helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring"

- name: helm install prometheus
  command: "helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring"
